package com.mycompany.eelectronics_iti;
// Generated Feb 26, 2018 3:42:38 AM by Hibernate Tools 4.3.1



/**
 * Admin generated by hbm2java
 */
public class Admin  implements java.io.Serializable {


     private Integer adminId;
     private String adminName;
     private String adminPassword;
     private String adminPhone;
     private String adminGender;
     private String adminCountry;
     private String adminEmail;

    public Admin() {
    }

    public Admin(String adminName, String adminPassword, String adminPhone, String adminGender, String adminCountry,String adminEmail) {
       this.adminName = adminName;
       this.adminPassword = adminPassword;
       this.adminPhone = adminPhone;
       this.adminGender = adminGender;
       this.adminCountry = adminCountry;
       this.adminEmail = adminEmail;
    }
   
    public Integer getAdminId() {
        return this.adminId;
    }
    
    public void setAdminId(Integer adminId) {
        this.adminId = adminId;
    }
    public String getAdminName() {
        return this.adminName;
    }
    
    public void setAdminName(String adminName) {
        this.adminName = adminName;
    }
    public String getAdminPassword() {
        return this.adminPassword;
    }
    
    public void setAdminPassword(String adminPassword) {
        this.adminPassword = adminPassword;
    }
    public String getAdminPhone() {
        return this.adminPhone;
    }
    
    public void setAdminPhone(String adminPhone) {
        this.adminPhone = adminPhone;
    }
    public String getAdminGender() {
        return this.adminGender;
    }
    
    public void setAdminGender(String adminGender) {
        this.adminGender = adminGender;
    }
    public String getAdminCountry() {
        return this.adminCountry;
    }
    
    public void setAdminCountry(String adminCountry) {
        this.adminCountry = adminCountry;
    }

    public String getAdminEmail() {
        return adminEmail;
    }

    public void setAdminEmail(String adminEmail) {
        this.adminEmail = adminEmail;
    }




}


