package com.mycompany.eelectronics_iti;
// Generated Feb 26, 2018 3:42:38 AM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * Products generated by hbm2java
 */
public class Products  implements java.io.Serializable {


     private int productId;
     private String productName;
     private double productPrice;
     private String productCategory;
     private int productQuantity;
     private String productImage;
     private String productDescription;
     private Set orderses = new HashSet(0);

    public Products() {
    }

	
    public Products(int productId, String productName, int productPrice, String productCategory, int productQuantity, String productImage, String productDescription) {
        this.productId = productId;
        this.productName = productName;
        this.productPrice = productPrice;
        this.productCategory = productCategory;
        this.productQuantity = productQuantity;
        this.productImage = productImage;
        this.productDescription = productDescription;
    }
    public Products(int productId, String productName, int productPrice, String productCategory, int productQuantity, String productImage, String productDescription, Set orderses) {
       this.productId = productId;
       this.productName = productName;
       this.productPrice = productPrice;
       this.productCategory = productCategory;
       this.productQuantity = productQuantity;
       this.productImage = productImage;
       this.productDescription = productDescription;
       this.orderses = orderses;
    }
   
    public int getProductId() {
        return this.productId;
    }
    
    public void setProductId(int productId) {
        this.productId = productId;
    }
    public String getProductName() {
        return this.productName;
    }
    
    public void setProductName(String productName) {
        this.productName = productName;
    }
    public double getProductPrice() {
        return this.productPrice;
    }
    
    public void setProductPrice(double productPrice) {
        this.productPrice = productPrice;
    }
    public String getProductCategory() {
        return this.productCategory;
    }
    
    public void setProductCategory(String productCategory) {
        this.productCategory = productCategory;
    }
    public int getProductQuantity() {
        return this.productQuantity;
    }
    
    public void setProductQuantity(int productQuantity) {
        this.productQuantity = productQuantity;
    }
    public String getProductImage() {
        return this.productImage;
    }
    
    public void setProductImage(String productImage) {
        this.productImage = productImage;
    }
    public String getProductDescription() {
        return this.productDescription;
    }
    
    public void setProductDescription(String productDescription) {
        this.productDescription = productDescription;
    }
    public Set getOrderses() {
        return this.orderses;
    }
    
    public void setOrderses(Set orderses) {
        this.orderses = orderses;
    }




}


