package com.mycompany.eelectronics_iti;
// Generated Feb 26, 2018 3:42:38 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Users generated by hbm2java
 */
public class Users  implements java.io.Serializable {


     private Integer userId;
     private String userName;
     private String userEmail;
     private String userPassword;
     private String userGender;
     private String userPhone;
     private double userBalance;
     private String userAddress;
     private Set orderses = new HashSet(0);

    public Users() {
    }

	
    public Users(String userName, String userEmail, String userPassword, String userGender, String userPhone, double userBalance,String userAddress) {
        this.userName = userName;
        this.userEmail = userEmail;
        this.userPassword = userPassword;
        this.userGender = userGender;
        this.userPhone = userPhone;
        this.userBalance = userBalance;
        this.userAddress = userAddress;
    }
    public Users(String userName, String userEmail, String userPassword, String userGender, String userPhone, double userBalance, Set orderses,String userAddress) {
       this.userName = userName;
       this.userEmail = userEmail;
       this.userPassword = userPassword;
       this.userGender = userGender;
       this.userPhone = userPhone;
       this.userBalance = userBalance;
       this.orderses = orderses;
       this.userAddress = userAddress;
    }
   
    public Integer getUserId() {
        return this.userId;
    }
    
    public void setUserId(Integer userId) {
        this.userId = userId;
    }
    public String getUserName() {
        return this.userName;
    }
    
    public void setUserName(String userName) {
        this.userName = userName;
    }
    public String getUserEmail() {
        return this.userEmail;
    }
    
    public void setUserEmail(String userEmail) {
        this.userEmail = userEmail;
    }
    public String getUserPassword() {
        return this.userPassword;
    }
    
    public void setUserPassword(String userPassword) {
        this.userPassword = userPassword;
    }
    public String getUserGender() {
        return this.userGender;
    }
    
    public void setUserGender(String userGender) {
        this.userGender = userGender;
    }
    public String getUserPhone() {
        return this.userPhone;
    }
    
    public void setUserPhone(String userPhone) {
        this.userPhone = userPhone;
    }
    public double getUserBalance() {
        return this.userBalance;
    }
    
    public void setUserBalance(double userBalance) {
        this.userBalance = userBalance;
    }
    public Set getOrderses() {
        return this.orderses;
    }
    
    public void setOrderses(Set orderses) {
        this.orderses = orderses;
    }

    public String getUserAddress() {
        return userAddress;
    }

    public void setUserAddress(String userAddress) {
        this.userAddress = userAddress;
    }




}


